version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: provisioning-service-mongodb
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: provisioning-service
    volumes:
      - ./data:/data/db